version: '3.9'
services:
  app:
    container_name: pvQ
    build: .
  networks:
    - pvQ-network
  proxy:
    container_name: pvQ-proxy
    image: nginx:alpine
    networks:
      - pvQ-network
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

networks:
  pvQ-network:
